COUNTRIES = {
    "pe": {
        "code": "pe",
        "nombre": "Perú",
        "bandera": "🇵🇪",
        "bandera_svg": "per.svg",
        "telefono": "+51 943 567 445",
        "whatsapp_link": "https://wa.link/sht6gi",
        "email": "contacto@cgmrental.com",
        "facebook": "https://www.facebook.com/CGMRENTAL/",
        "instagram": "https://www.instagram.com/cgmrental/",
        "linkedin": "https://pe.linkedin.com/company/cgm-rental",
        "youtube": "https://www.youtube.com/@cgmrental2049",
        "ciudad_principal": "Lima",
        "direccion": "Carretera Panamericana Sur Km. 30.5, San Pedro, Lurín",
        "lat": -12.2520, "lng": -76.8810,
        "sucursales": [
            {"nombre": "Lima",     "tipo": "principal",  "direccion": "Carretera Panamericana Sur Km. 30.5, San Pedro, Lurín",               "telefono": "", "lat": -12.2520, "lng": -76.8810},
            {"nombre": "Piura",    "tipo": "sucursal",   "direccion": "Zona Industrial J1-J2 Mz B Lt. 13, Distrito Veintiseis de Octubre",   "telefono": "", "lat": -5.1871,  "lng": -80.6322},
            {"nombre": "Chilca",   "tipo": "sucursal",   "direccion": "Parque Industrial SECTOR 62, Mz. A, Lote A-6, Primera Etapa",        "telefono": "", "lat": -12.5190, "lng": -76.7270},
            {"nombre": "Cusco",    "tipo": "sucursal",   "direccion": "Carretera Cusco-Urcos Km 15.5, Oropesa",                             "telefono": "", "lat": -13.6170, "lng": -71.8270},
            {"nombre": "Arequipa", "tipo": "sucursal",   "direccion": "Vía de Evitamiento Km 4.1 Irrigación Zamacola, Cerro Colorado",      "telefono": "", "lat": -16.3600, "lng": -71.5800},
            {"nombre": "Trujillo", "tipo": "atencion",   "direccion": "Prolongación Cesar Vallejo Oeste 1206, Urb. San Eloy",                "telefono": "", "lat": -8.1120,  "lng": -79.0440},
            {"nombre": "Ica",      "tipo": "atencion",   "direccion": "Panamericana Sur Km. 295 El Cambio, Macacona, Subtanjalla",           "telefono": "", "lat": -13.9490, "lng": -75.7650},
            {"nombre": "Pucallpa", "tipo": "atencion",   "direccion": "Av. Unión Mz. E Lt. 1, AAHH Frida Arce",                            "telefono": "", "lat": -8.3790,  "lng": -74.5530},
        ],
        # Links del pie de página
        "bolsa_trabajo_url":      "https://docs.google.com/forms/d/e/1FAIpQLSeAQgGJAquZ6bHjm9I_8wrKpAtVrfIFxXKi9xmKzIUqAKqdQA/viewform",
        "operadores_url":         "https://www.facebook.com/cgmrenta.capacita?locale=es_LA",
        "huella_carbono_url":     "https://drive.google.com/file/d/1WM6X0xEuMAajVQAzNCuyJSKEt_la5GOl/view",
        "libro_reclamaciones_url":"https://docs.google.com/forms/d/e/1FAIpQLSdJmM4ve1HR4jrq_1gXtt8Y7KZYaGhzM3o34ZdcF9iZSDBGcA/viewform",
        # Flags
        "show_mineria": True,
        "show_agricola": True,
        "show_energia": True,
        "show_usados": True,
        "show_leasing": True,
        "show_portal_proveedores": True,
        "moneda": "S/.",
    },
    "ar": {
        "code": "ar",
        "nombre": "Argentina",
        "bandera": "🇦🇷",
        "bandera_svg": "arg.svg",
        "telefono": "+54 9 11 7900 0648",
        "whatsapp_link": "https://wa.me/5491179000648",
        "email": "contacto@cgmrental.com",
        "facebook": "https://www.facebook.com/CGMRENTAL/",
        "instagram": "https://www.instagram.com/cgmrental/",
        "linkedin": "https://www.linkedin.com/company/cgm-rental/",
        "youtube": "https://www.youtube.com/@cgmrental2049",
        "ciudad_principal": "San Juan",
        "direccion": "Avenida Libertador 521 - 4to piso, San Juan",
        "lat": -31.5360, "lng": -68.5310,
        "sucursales": [
            {"nombre": "San Juan (Sede Principal)", "tipo": "principal", "direccion": "Avenida Libertador 521 - 4to piso, San Juan", "telefono": "", "lat": -31.5360, "lng": -68.5310},
        ],
        # Links del pie de página
        "bolsa_trabajo_url":      "https://www.linkedin.com/company/cgm-rental/jobs/",
        "operadores_url":         "",
        "huella_carbono_url":     "",
        "libro_reclamaciones_url":"https://docs.google.com/forms/d/e/1FAIpQLSdJmM4ve1HR4jrq_1gXtt8Y7KZYaGhzM3o34ZdcF9iZSDBGcA/viewform",
        "moneda": "ARS",
        # Flags
        "show_mineria": True,
        "show_agricola": False,
        "show_energia": False,
        "show_usados": False,
        "show_leasing": False,
        "show_portal_proveedores": False,
    }
}

DEFAULT_COUNTRY = "pe"
