COUNTRIES = {
    "pe": {
        "code": "pe",
        "nombre": "Perú",
        "bandera": "🇵🇪",
        "bandera_svg": "per.svg",
        "telefono": "+51 943 567 445",
        "whatsapp_link": "https://wa.link/sht6gi",
        "email": "contacto@cgmrental.com",
        "facebook": "https://www.facebook.com/CGMRENTAL/",
        "instagram": "https://www.instagram.com/cgmrental/",
        "linkedin": "https://pe.linkedin.com/company/cgm-rental",
        "youtube": "https://www.youtube.com/@cgmrental2049",
        "ciudad_principal": "Lima",
        "direccion": "Carretera Panamericana Sur Km. 30.5, San Pedro, Lurín",
        "lat": -12.2773, "lng": -76.8864,
        "sucursales": [
            {"nombre": "Lima",     "tipo": "principal",  "direccion": "Carretera Panamericana Sur Km. 30.5, San Pedro, Lurín",               "telefono": "", "lat": -12.2773, "lng": -76.8864, "maps_url": "https://maps.app.goo.gl/ax7uqywA783GZrgV6"},
            {"nombre": "Piura",    "tipo": "sucursal",   "direccion": "Zona Industrial J1-J2 Mz B Lt. 13, Distrito Veintiseis de Octubre",   "telefono": "", "lat": -5.1746,  "lng": -80.6760, "maps_url": "https://maps.app.goo.gl/VM6Li2x5G4eDPRTp9"},
            {"nombre": "Chilca",   "tipo": "sucursal",   "direccion": "Parque Industrial SECTOR 62, Mz. A, Lote A-6, Primera Etapa",        "telefono": "", "lat": -12.5021, "lng": -76.7418, "maps_url": "https://maps.app.goo.gl/g5JLmuKCSpWGtHvb9"},
            {"nombre": "Cusco",    "tipo": "sucursal",   "direccion": "Carretera Cusco-Urcos Km 16.5, Oropesa",                             "telefono": "", "lat": -13.5826, "lng": -71.8105, "maps_url": "https://maps.app.goo.gl/Y9WKjZqoqArBoipK7"},
            {"nombre": "Arequipa", "tipo": "sucursal",   "direccion": "Vía de Evitamiento Km 5.1, Cerro Colorado",                         "telefono": "", "lat": -16.3623, "lng": -71.5781, "maps_url": "https://maps.app.goo.gl/WVkgECApFrkNdZwu7"},
            {"nombre": "Trujillo", "tipo": "atencion",   "direccion": "Prolongación Cesar Vallejo Oeste 1206, Urb. San Eloy",                "telefono": "", "lat": -8.0945,  "lng": -79.0264, "maps_url": "https://maps.app.goo.gl/uh7qawHXhRixujsE8"},
            {"nombre": "Ica",      "tipo": "atencion",   "direccion": "Panamericana Sur Km. 295 El Cambio, Macacona, Subtanjalla",           "telefono": "", "lat": -14.0190, "lng": -75.7624, "maps_url": "https://maps.app.goo.gl/zsDtBtZX5r4ZXhRh8"},
            {"nombre": "Pucallpa", "tipo": "atencion",   "direccion": "Unión 1199, Pucallpa 25000",                                         "telefono": "", "lat": -8.3797,  "lng": -74.5542, "maps_url": "https://maps.app.goo.gl/Z9KaXMwrg7z1oDG56"},
        ],
        # Links del pie de página
        "bolsa_trabajo_url":      "https://docs.google.com/forms/d/e/1FAIpQLSeAQgGJAquZ6bHjm9I_8wrKpAtVrfIFxXKi9xmKzIUqAKqdQA/viewform",
        "operadores_url":         "https://www.facebook.com/cgmrenta.capacita?locale=es_LA",
        "huella_carbono_url":     "https://drive.google.com/file/d/1WM6X0xEuMAajVQAzNCuyJSKEt_la5GOl/view",
        "libro_reclamaciones_url":"https://docs.google.com/forms/d/e/1FAIpQLSdJmM4ve1HR4jrq_1gXtt8Y7KZYaGhzM3o34ZdcF9iZSDBGcA/viewform",
        # Flags
        "show_mineria": True,
        "show_agricola": True,
        "show_energia": True,
        "show_usados": True,
        "show_leasing": True,
        "show_portal_proveedores": True,
        "moneda": "S/.",
    },
    "ar": {
        "code": "ar",
        "nombre": "Argentina",
        "bandera": "🇦🇷",
        "bandera_svg": "arg.svg",
        "telefono": "+54 9 11 7900 0648",
        "whatsapp_link": "https://wa.me/5491179000648",
        "email": "contacto@cgmrental.com",
        "facebook": "https://www.facebook.com/CGMRENTAL/",
        "instagram": "https://www.instagram.com/cgmrental/",
        "linkedin": "https://www.linkedin.com/company/cgm-rental/",
        "youtube": "https://www.youtube.com/@cgmrental2049",
        "ciudad_principal": "San Juan",
        "direccion": "Avenida Libertador 521 - 4to piso, San Juan",
        "lat": -31.5347, "lng": -68.5337,
        "sucursales": [
            {"nombre": "San Juan (Sede Principal)", "tipo": "principal", "direccion": "Avenida Libertador 521 - 4to piso, San Juan", "telefono": "", "lat": -31.5347, "lng": -68.5337, "maps_url": ""},
        ],
        # Links del pie de página
        "bolsa_trabajo_url":      "https://www.linkedin.com/company/cgm-rental/jobs/",
        "operadores_url":         "",
        "huella_carbono_url":     "",
        "libro_reclamaciones_url":"https://docs.google.com/forms/d/e/1FAIpQLSdJmM4ve1HR4jrq_1gXtt8Y7KZYaGhzM3o34ZdcF9iZSDBGcA/viewform",
        "moneda": "ARS",
        # Flags
        "show_mineria": True,
        "show_agricola": False,
        "show_energia": False,
        "show_usados": False,
        "show_leasing": False,
        "show_portal_proveedores": False,
    }
}

DEFAULT_COUNTRY = "pe"
